### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/developerdao.com#110] opened 2021-09-23 09:28 UTC
Maybe we can add an about page that has some information on what the DAO is, why it was made, what are we working on, what's the point of the website, etc etc. Just a thought

**Comment by Dhaiwat10** [comment] 2021-09-23 09:30
I noticed the readme of this repo already has some great info. Maybe we can build on top of that.

**Comment by codingwithmanny** [comment] 2021-09-23 21:12
I almost want this as a future feature because I think we're still trying to figure that out at the moment (that's my opinion). I know that @kempsterrrr did come up with the Manifesto, so maybe it's that?
https://github.com/Developer-DAO/community/pull/7/files

**Comment by Dhaiwat10** [comment] 2021-09-23 21:36
Yeah. Something like that would fit well.

**Comment by dizthewize** [comment] 2021-11-12 06:14
@Dhaiwat10 @codingwithmanny are there designs out for what this page should look like yet?

**Comment by gjsyme** [comment] 2021-11-12 06:56
Not that I'm aware of. We anticipate that there will be a clearer path
forward after the town hall later today.

**Comment by dizthewize** [comment] 2021-11-12 07:01
@gjsyme okay thank you I would like to take this on if no one has picked it up yet

**Comment by Dhaiwat10** [comment] 2021-11-12 07:34
@dizthewize I think you should wait until we have the design/content ready

**Comment by amazingandyyy** [comment] 2021-11-15 17:45
@gjsyme in that case, can we add a `pending` or `blocked` flag to the PR, I really push to make our newcomer easier to find an issue to help on

**Comment by with-heart** [comment] 2021-11-16 12:40
I'm actually going to close this since priorities are going to be driven by design guild. We'll let them decide how they want to break the site down into pages, what the design/style looks like (based on Chakra, of course!), etc.

**Closed by with-heart** 2021-11-16 12:40 UTC
Labels: enhancement
