### ISSUE TITLE
Make local and commit deployments point to testnet for minting

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developerdao.com#155] opened 2021-10-30 04:46 UTC
### Context / Background / How This Idea Came To Fruition

After completion of #147 we realized that the minting functionality is always pointing to mainnet regardless of where the application is running.  This poses a hinderance wrt to testing locally and in a test environment when trying to actually mint since in the current form it will cost real ETH to preform. 

### Problem / Opportunity

With this change, developers working on future Ethereum blockchain features will connect to the Rinkeby testnet when working locally and testing on each per-commit deploy

### Proposed Solution / How It Can Be Improved

We will solve this issue by having an env based config to point to the Rinkeby testnet locally and on each pre-commit deploy while remaining mainnet in PROD(exact implementation is left to the developer).  The current Infura id can be used on all environments but we have to make code changes in [DirectMint](https://github.com/Developer-DAO/developerdao.com/blob/main/src/components/DirectMint/DirectMint.tsx) among other spots to account for the Rinkeby testnet.   Furthermore, since the Infura ID is stored as an env variable on Vercel the implementer of this issue will need to update the README file to note that any developer working on the codebase will need to have the infura id sent to them by a developerdao.com team member.

Please use `0xbf114c4cbb4e70e6098589a918c84292cb40602a` as the DEVS contract address when coding for the testnet and `https://rinkeby.etherscan.io/tx/` as the ETHERSCAN link prefix for the verification link.

### Testing the changes

Testing the changes will require potentially updating the e2e tests once #154 is complete in addition to manual smoke testing the existing minting functionality.

If you require Rinkeby testnet ETH please use the following [Chainlink faucet](https://faucets.chain.link/rinkeby?_ga=2.175183204.735297823.1635568853-1702889432.1630879734) to obtain some.

### Additional Information

Please ping the developerdao.com team in the Discord channel to ask for the infura ID before starting work on this issue

**Comment by narbs91** [comment] 2021-10-30 17:29
@kavimaluskam has said he would like to work no this

**Comment by kavimaluskam** [comment] 2021-11-02 21:31
Have been mainly following up the work by @codingwithmanny these days. 

Like to clarify, are we aiming to do the local hardhat approach or testnet approach on local and ci in #154,

meanwhile we can allow user to do manual testing with their local webserver by `yarn dev`, where testnet contract are configured?

**Comment by narbs91** [comment] 2021-11-03 00:34
Heya @kavimaluskam so issue 154 is a separate thing all together were we're trying to figure out a way to mock wallet interaction; whereas with 155, what we are looking to solve is the problem of the minting page always pointing to mainnet.  What we want to do is have the app point to the rinkeby testnet contract (`0xbf114c4cbb4e70e6098589a918c84292cb40602a`)  when running locally and ideally on the per-commit deploy (i.e. when someone pushes a commit to a PR).  This way people working on the minting page don't have to use real ETH to mint/interact with the contract.  You can have a look at the reverted changes on this [commit](https://github.com/Developer-DAO/developerdao.com/pull/147/commits/eb5de748ded26592c5c9836e961c118f8aadd4c5) of the Direct minting PR for an idea of how to start.  Hope that makes things at least a bit clearer

**Comment by kavimaluskam** [comment] 2021-11-03 09:27
yea I confused myself and it makes more sense now.

**Comment by kavimaluskam** [comment] 2021-11-03 10:38
Added a PR here https://github.com/Developer-DAO/developerdao.com/pull/162.

Tested on local and looks good.
Not sure if there are any better way to handle the constants with condition.

**Comment by codingwithmanny** [comment] 2021-11-03 13:47
@kavimaluskam @narbs91 
To add to the clarification or lack on my part in terms of what I'd like to see (would also like to know what you guys think) is:

1 - Unit tests are mocked with jest in CI / GHA
2 - E2E tests are run with `localhost` contract with Cypress in CI / GHA
3 - Deployed Vercel PRs are run against `testnet` (might need some env variables set up for this)

That's my idea, but would to see if there are holes for this direction.

**Comment by narbs91** [comment] 2021-11-04 03:41
1. ✅ 
2. Do you mean deploying the contract to a docker container per-commit and running the tests against that?
3. We'd need ti dig a bit into Vercel but they do support a "per env" set up for the variables:
![image](https://user-images.githubusercontent.com/29411347/140253903-3ae4c07e-a9f6-478c-a0ad-2302d8e1b3b3.png)
I think it should be possible but typically these things are driven by configuration files in the project themselves.  I know how to do it in Java with pre environment .yml files (i.e spring) but don't know if the same thing can be applied to in this context.  I'll see if i can research this a bit as it'll be a real nice thing to have; however, it would seem with the way the project is setup there is no concept of test vs. int vs. prod as everything seems to be prod.

**Comment by narbs91** [comment] 2021-11-04 04:47
This looks like a pretty promising library we might be able to use: https://github.com/lorenwest/node-config

It's pretty much what i had in my head with the previous comment

**Comment by with-heart** [comment] 2021-11-04 12:39
Next.js defaults to handling environment variables files, where we can use `.env.(development|test|production)` (checked in) to store shared vars and `.env.(development|test|production).local` (in `.gitignore`) to store sensitive vars.

`build` defaults to using `production` but we should be able to override that by overriding `NODE_ENV` e.g. `NODE_ENV=test next build`.

Not sure if that helps because I'm not entirely sure I understand the use case here, but it seems like `node-config` is doing basically that with a little extra flexibility.

**Comment by codingwithmanny** [comment] 2021-11-04 14:30
> 2\. the contract to a docker container per-commit and running the tests against that?

Re: 2. Yes, we would just push the contract to a Docker Hub image instance and just pull it to run with the GHA tests. I'm trying to get this setup to explain this a bit further as well. Once it is setup, then it's all gravy...mmm... poutine.

Re: 3. Worse case we create different env variable names that we just reference.

Ex:
```
CONTRACT_ADDRESS_DEV, CONTRACT_ADDRESS_STAGING, CONTRACT_ADDRESS_PROD
```

```js
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS_PROD || process.env.CONTRACT_ADDRESS_STAGING || process.env.CONTRACT_ADDRESS_DEV;
```

**Comment by with-heart** [comment] 2021-11-04 14:58
> then it's all gravy...mmm... poutine

Thanks for making me unbelievably hungry 🤤

**Comment by kavimaluskam** [comment] 2021-11-04 16:03
> @kavimaluskam @narbs91 To add to the clarification or lack on my part in terms of what I'd like to see (would also like to know what you guys think) is:
> 
> 1 - Unit tests are mocked with jest in CI / GHA 2 - E2E tests are run with `localhost` contract with Cypress in CI / GHA 3 - Deployed Vercel PRs are run against `testnet` (might need some env variables set up for this)
> 
> That's my idea, but would to see if there are holes for this direction.

Is 3) means by the testing on CI when merge / preview build?

**Comment by codingwithmanny** [comment] 2021-11-04 16:33
@kavimaluskam crap yeah that's true. Not really a way to reset that testnet minting is there... or is there? Honestly asking lol.

**Comment by kavimaluskam** [comment] 2021-11-04 16:44
Does deploy a new contract everytime for testing make sense? In this sense we have to maintain an account with sufficient testnet ETH, and probably bare the longer time in CI for testnet transactions.

Or another simpler (weaker approach) is just providing testnet testing by manual approach.

Also I'm not sure what's the best solution in this domain here 🪖

**Comment by codingwithmanny** [comment] 2021-11-04 17:05
Just rethinking this. This is really for smoke testing, so there isn't any automated tests. So maybe it's still a viable solution.

**Comment by kavimaluskam** [comment] 2021-11-04 17:43
Is local + testnet setup sufficient for smoke testing? I think it's good to have mainnet production preview on vercel afterall.

**Comment by codingwithmanny** [comment] 2021-11-05 21:16
@kavimaluskam yeah I guess my thinking was to use testnet like a staging (which is as close as production as possible), but the issue is that you can't reset staging in this case to get it to be the most up to date. So maybe you're right about that, it should be mainnet because staging can't really be trusted.

**Comment by kavimaluskam** [comment] 2021-11-06 14:37
@codingwithmanny Yeah... reseting staging is so tricky in testnet v.s. mainnet.

So i guess setting up testnet is sufficient for devs to the manually testing on local?
And we can still setup staging testnet by env @ vercel later if we need to.

**Closed** 2021-11-09 01:49 UTC
Labels: enhancement

**Comment by codingwithmanny** [comment] 2021-11-11 15:12
Works for me.
